#!/usr/bin/env bash
# Install Playwright + chromium + its runtime shared libraries.
#
# If you have sudo: this just runs `npx playwright install --with-deps chromium`.
# If you don't: we download the required .deb packages and extract their .so
# files into ~/.local/lib/playwright-libs. Then set LD_LIBRARY_PATH when running.
#
# A helper is written to e2e/run-playwright.sh that sources the right
# LD_LIBRARY_PATH and forwards its args to `npx playwright`.

set -euo pipefail
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
source "$SCRIPT_DIR/_common.sh"

cd "$ROOT/e2e"

if [ ! -d node_modules ]; then
  log "installing e2e npm deps"
  npm install
fi

if sudo -n true 2>/dev/null; then
  log "sudo available — using playwright's --with-deps installer"
  sudo npx playwright install --with-deps chromium
  cat >"$ROOT/e2e/run-playwright.sh" <<'EOF'
#!/usr/bin/env bash
cd "$(dirname "$0")"
exec npx playwright "$@"
EOF
  chmod +x "$ROOT/e2e/run-playwright.sh"
  exit 0
fi

log "no sudo — installing chromium via npm and shared libs via .deb extraction"

npx playwright install chromium

# Detect distro; we only support Ubuntu/Debian for the no-sudo path
if ! [ -f /etc/debian_version ]; then
  log "no-sudo install only supports Debian/Ubuntu-derived distros."
  log "install these packages globally: libnspr4 libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libxkbcommon0 libatspi2.0-0 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 libgbm1 libdrm2 libasound2 libpangocairo-1.0-0 libpango-1.0-0 libcairo2"
  exit 1
fi

libs_dir="$HOME/.local/lib/playwright-libs"
deps_dir="$HOME/.local/lib/playwright-deps"
mkdir -p "$libs_dir" "$deps_dir"
cd "$deps_dir"

# Suffix-insensitive names — apt resolves t64/codename variants.
packages=(
  libnspr4 libnss3
  "libatk1.0-0t64|libatk1.0-0"
  "libatk-bridge2.0-0t64|libatk-bridge2.0-0"
  "libcups2t64|libcups2"
  libxkbcommon0
  "libatspi2.0-0t64|libatspi2.0-0"
  libxcomposite1 libxdamage1 libxfixes3 libxrandr2
  libgbm1 libdrm2
  "libasound2t64|libasound2"
  libpangocairo-1.0-0 libpango-1.0-0 libcairo2
)

for entry in "${packages[@]}"; do
  downloaded=0
  IFS='|' read -ra alts <<<"$entry"
  for pkg in "${alts[@]}"; do
    if apt-get download -q "$pkg" >/dev/null 2>&1; then
      downloaded=1
      break
    fi
  done
  [ "$downloaded" = "1" ] || log "warning: none of [${alts[*]}] downloadable"
done

mkdir -p "$deps_dir/extracted"
for f in "$deps_dir"/*.deb; do
  [ -f "$f" ] || continue
  dpkg-deb -x "$f" "$deps_dir/extracted/"
done

find "$deps_dir/extracted" -name "*.so*" -exec cp -a {} "$libs_dir/" \;

cat >"$ROOT/e2e/run-playwright.sh" <<EOF
#!/usr/bin/env bash
# Auto-generated by install/install-playwright.sh. Sources the locally-built
# chromium runtime libs and runs playwright.
set -euo pipefail
cd "\$(dirname "\$0")"
export LD_LIBRARY_PATH="\$HOME/.local/lib/playwright-libs:\${LD_LIBRARY_PATH:-}"
exec npx playwright "\$@"
EOF
chmod +x "$ROOT/e2e/run-playwright.sh"

log "playwright ready — use: ./e2e/run-playwright.sh test"
