#!/usr/bin/env bash
# Single toggle for running this template behind an enterprise MITM proxy
# (Zscaler, Netskope, Prisma Access, etc.).
#
# enable <path>   Copy a PEM into certs/enterprise-ca.crt, write env exports
#                 to certs/enterprise-ca.env, and (best-effort) install into
#                 the host system trust store.
# disable         Remove certs/enterprise-ca.crt + env file. Tells you the
#                 sudo command to remove from system trust if you want to.
# status          Show whether the toggle is on, fingerprint, env paths.
# env             Print `export VAR=...` lines on stdout. Source it from your
#                 shell:  eval "$(scripts/enterprise-cert.sh env)"
# verify <url>    curl + openssl s_client against <url> to confirm the cert
#                 chain validates with the bundle.
#
# This script never edits .env. Compose picks the cert up at build time by
# COPYing the certs/ directory; install scripts source certs/enterprise-ca.env
# automatically when present. Nothing else is wired up out of band.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CERTS_DIR="$REPO_ROOT/certs"
CERT_PATH="$CERTS_DIR/enterprise-ca.crt"
ENV_PATH="$CERTS_DIR/enterprise-ca.env"

cmd="${1:-status}"

log()  { printf '[enterprise-cert] %s\n' "$*" >&2; }
fail() { printf '[enterprise-cert] ERROR: %s\n' "$*" >&2; exit 1; }

write_env_file() {
  # Single source of truth for which env vars need to be set so that every
  # CLI we shell out to trusts the enterprise CA. Sourced by install/_common.sh
  # and printable via `enterprise-cert.sh env`.
  cat >"$ENV_PATH" <<EOF
# Auto-generated by scripts/enterprise-cert.sh. Do not edit by hand.
# Source this from a shell to make the current process trust the enterprise CA.
export ENTERPRISE_CA_BUNDLE="$CERT_PATH"
export NODE_EXTRA_CA_CERTS="$CERT_PATH"
export SSL_CERT_FILE="$CERT_PATH"
export REQUESTS_CA_BUNDLE="$CERT_PATH"
export CURL_CA_BUNDLE="$CERT_PATH"
export GIT_SSL_CAINFO="$CERT_PATH"
export AWS_CA_BUNDLE="$CERT_PATH"
EOF
  chmod 644 "$ENV_PATH"
}

install_to_host_trust() {
  # Best-effort. Failure here is not fatal — the per-tool env vars cover the
  # tools the template actually uses. System trust is a nice-to-have for
  # browsers and ad-hoc curl outside this repo.
  case "$(uname -s)" in
    Darwin)
      log "to add to macOS system trust (optional, requires sudo):"
      log "  sudo security add-trusted-cert -d -r trustRoot \\"
      log "    -k /Library/Keychains/System.keychain $CERT_PATH"
      ;;
    Linux)
      if [ -d /usr/local/share/ca-certificates ] && command -v update-ca-certificates >/dev/null 2>&1; then
        if sudo -n true 2>/dev/null; then
          log "installing into Linux system trust (sudo, debian-family)"
          sudo install -m 0644 "$CERT_PATH" /usr/local/share/ca-certificates/enterprise-ca.crt
          sudo update-ca-certificates >/dev/null
        else
          log "to add to Linux system trust (optional, debian-family):"
          log "  sudo install -m 0644 $CERT_PATH /usr/local/share/ca-certificates/enterprise-ca.crt"
          log "  sudo update-ca-certificates"
        fi
      elif [ -d /etc/pki/ca-trust/source/anchors ]; then
        log "to add to Linux system trust (optional, RHEL-family):"
        log "  sudo install -m 0644 $CERT_PATH /etc/pki/ca-trust/source/anchors/enterprise-ca.crt"
        log "  sudo update-ca-trust"
      fi
      ;;
  esac
}

cert_fingerprint() {
  if command -v openssl >/dev/null 2>&1 && [ -s "$CERT_PATH" ]; then
    openssl x509 -in "$CERT_PATH" -noout -fingerprint -sha256 2>/dev/null | sed 's/^/  /'
    openssl x509 -in "$CERT_PATH" -noout -subject 2>/dev/null | sed 's/^/  /'
    openssl x509 -in "$CERT_PATH" -noout -enddate 2>/dev/null | sed 's/^/  /'
  fi
}

case "$cmd" in
  enable)
    src="${2:-}"
    [ -n "$src" ] || fail "usage: $0 enable <path-to-pem>"
    [ -f "$src" ] || fail "no such file: $src"
    if ! openssl x509 -in "$src" -noout >/dev/null 2>&1; then
      fail "$src does not parse as a PEM certificate (is it the right file?)"
    fi
    mkdir -p "$CERTS_DIR"
    install -m 0644 "$src" "$CERT_PATH"
    write_env_file
    log "wrote $CERT_PATH"
    log "wrote $ENV_PATH"
    cert_fingerprint
    install_to_host_trust
    log ""
    log "next steps:"
    log "  1. eval \"\$(scripts/enterprise-cert.sh env)\"  # current shell"
    log "  2. add to your shell rc to make it permanent (or just for this repo dir)"
    log "  3. ./rebuild.sh   # rebuilds containers with the cert baked in"
    ;;

  disable)
    rm -f "$CERT_PATH" "$ENV_PATH"
    log "removed $CERT_PATH and $ENV_PATH"
    log "rebuild containers (./rebuild.sh) to drop the cert from images."
    case "$(uname -s)" in
      Linux)
        if [ -f /usr/local/share/ca-certificates/enterprise-ca.crt ]; then
          log "to also remove from host trust (optional):"
          log "  sudo rm /usr/local/share/ca-certificates/enterprise-ca.crt && sudo update-ca-certificates --fresh"
        fi
        ;;
      Darwin)
        log "to also remove from macOS system trust (optional):"
        log "  sudo security delete-certificate -c '<subject CN>' /Library/Keychains/System.keychain"
        ;;
    esac
    ;;

  status)
    if [ -s "$CERT_PATH" ]; then
      log "ENABLED — $CERT_PATH ($(wc -c <"$CERT_PATH" | tr -d ' ') bytes)"
      cert_fingerprint
      [ -f "$ENV_PATH" ] && log "env file: $ENV_PATH" || log "env file MISSING — run: scripts/enterprise-cert.sh enable <path>"
    else
      log "DISABLED — no cert at $CERT_PATH"
    fi
    ;;

  env)
    [ -f "$ENV_PATH" ] || fail "no env file at $ENV_PATH (run: $0 enable <path>)"
    cat "$ENV_PATH"
    ;;

  verify)
    url="${2:-}"
    [ -n "$url" ] || fail "usage: $0 verify <url>"
    [ -s "$CERT_PATH" ] || fail "no cert installed (run: $0 enable <path>)"
    log "curl --cacert $CERT_PATH $url"
    curl -fsS --cacert "$CERT_PATH" -o /dev/null -w 'HTTP %{http_code} (%{time_total}s)\n' "$url"
    ;;

  *)
    cat >&2 <<EOF
usage: $0 <command>
  enable <pem>     install the enterprise CA into this repo
  disable          remove the cert + env from this repo
  status           show current state, fingerprint, expiry
  env              print export lines (eval the output to apply to current shell)
  verify <url>     curl-test the cert against <url>
EOF
    exit 2
    ;;
esac
